import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    // @ts-ignore
    <html lang="en" class='dark'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
